version: "3.8"

services:

  mysql:
    container_name: mysql
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    volumes:
      - type: volume
        source: mysql-phpstorm
        target: /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - ${DOCKER_MYSQL_PORT}:3306
    networks:
      - phpstorm-network

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    restart: unless-stopped
    environment:
      - PMA_USER=${MYSQL_USER}
      - PMA_PASSWORD=${MYSQL_PASSWORD}
      - PMA_HOST=mysql
      - PMA_ARBITRARY=0
    links:
      - mysql
    ports:
      - ${DOCKER_PMA_PORT}:80
    networks:
      - phpstorm-network

  php-fpm:
    image: awesome/php
    build: ./docker/image/php
    restart: unless-stopped
    volumes:
      - "./:/code"
    networks:
      - phpstorm-network

  nginx:
    image: awesome/nginx
    build: ./docker/image/nginx
    restart: unless-stopped
    depends_on:
      - php-fpm
      - mysql
    volumes:
      - "./:/code"
    ports:
      - ${DOCKER_NGINX_PORT}:80
    environment:
      - DOCKER_NGINX_HOST=${DOCKER_NGINX_HOST}
    networks:
      - phpstorm-network

networks:
  phpstorm-network:

volumes:
  mysql-phpstorm:
