version: "3"

services:
  mysql:
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./docker/volume/mysql
        target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - phpstorm-backend

  php:
#    image: awesome/php
#    build: ./docker/image/php
    image: phpstorm/php-apache:8.2-xdebug3.2
    restart: unless-stopped
    environment:
      - MYSQL_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/${MYSQL_DATABASE}?serverVersion=8.0
    links:
      - mysql
    volumes:
      - ".:/var/www"
    networks:
      - phpstorm-backend
      - phpstorm-frontend

  nginx:
    image: nginx:latest
    restart: unless-stopped
    depends_on:
      - php
      - mysql
    volumes:
      - ".:/var/www"
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    expose:
      - 80
    ports:
      - "8888:80"
    networks:
      - phpstorm-backend
      - phpstorm-frontend

#volumes:
#  ${MYSQL_NAME}-volume:/var/lib/mysql:

networks:
  phpstorm-backend:
  phpstorm-frontend:
