version: "3"
name: "phpstorm"
  
services:
  mysql:
    image: mysql/mysql-server:8.0
    restart: on-failure
    volumes:
      - type: bind
        source: ./docker/volumes/mysql
        target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - backend

  php:
    image: awesome/php
    build: ./docker/php
    restart: on-failure
    depends_on:
      - mysql
    environment:
      - MYSQL_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:3306/${MYSQL_DATABASE}?serverVersion=8.0
    links:
      - mysql
    volumes:
      - ".:/var/www"
    networks:
      - backend
      - frontend

  nginx:
    image: nginx:latest
    restart: on-failure
    depends_on:
      - php
      - mysql
    volumes:
      - ".:/var/www"
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    expose:
      - 80
    ports:
      - "8888:80"
    networks:
      - backend
      - frontend

#volumes:
#  ${MYSQL_NAME}-volume:/var/lib/mysql:

networks:
  backend:
  frontend:
